language: node_js
branches:
  only:
    - master
node_js:
  - "10"
install:
  - npm install -g serverless
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run coveralls
  - AWS_ACCESS_KEY_ID=$aws_access_key_id AWS_SECRET_ACCESS_KEY=$aws_secret_access_key sls deploy
cache:
  directories:
    - node_modules
