Resources:
  RegionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.moviesTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: contentId
          AttributeType: S
        - AttributeName: language
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
      GlobalSecondaryIndexes:
        - IndexName: contentId-index
          KeySchema:
            - AttributeName: contentId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
        - IndexName: language-index
          KeySchema:
            - AttributeName: language
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: ${self:custom.tableThroughput}
            WriteCapacityUnits: ${self:custom.tableThroughput}
